### ISSUE TITLE
U.are.U skd Needed

### ISSUE THREAD

**Issue by Yazeeiyd** [ankit4u3/Digital-Persona#3]
please i cant find the SDK in the project folder please assist

**Comment by Yazeeiyd** [comment]
and i get this error
Exception in thread "main" java.lang.NoClassDefFoundError: com/digitalpersona/uareu/UareUException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.digitalpersona.uareu.UareUException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
